souderton_ward:
  boxes:
    - id: i-am-a-child-of-god
      image_url: https://www.lds.org/bc/content/shared/content/images/gospel-library/magazine/fr09jan41_color.jpg
      song_title: I am a child of God
      music_url: http://broadcast.lds.org/churchmusic/MP3/1/2/words/2.mp3?download=true
    - id: my-heavenly-father-loves-me
      image_url: https://easter-fun.info/wp-content/uploads/04/lds-easter-message-2018-easter-lily-1024x1024.jpg
      song_title: My Heavenly Father loves me
      music_url: http://broadcast.lds.org/churchmusic/MP3/1/2/words/228.mp3?download=true
    - id: when-i-am-baptized
      image_url: https://media.ldscdn.org/images/media-library/gospel-art/gospel-in-action/baptism-lds-593669-gallery.jpg
      song_title: When I am baptized
      music_url: http://media2.ldscdn.org/assets/music/childrens-songbook/2002-01-0920-when-i-am-baptized-words-and-music-192k-eng.mp3?download=true
    - id: families-can-be-together-forever
      image_url: https://www.lds.org/bc/content/ldsorg/church/news/2014/2/3/300%20family%20at%20temple.jpg
      song_title: Families can be together forever
      music_url: http://broadcast.lds.org/churchmusic/MP3/1/2/words/188.mp3?download=true
    - id: a-childs-prayer
      image_url: https://media.ldscdn.org/images/media-library/prayer/young-man-in-fiji-praying-268645-gallery.jpg
      song_title: A child's prayer
      music_url: http://broadcast.lds.org/churchmusic/MP3/1/2/words/12.mp3?download=true
    - id: if-the-savior-stood-beside-me
      image_url: https://media.ldscdn.org/images/media-library/gospel-art/gospel-in-action/jesus-children-37775-gallery.jpg
      song_title: If the Savior stood beside me
      music_url: http://broadcast.lds.org/churchmusic/Primary/PR_IfTheSavior_eng.mp3?download=true
souderton_ward_test:
  boxes:
    - id: i-am-a-child-of-god
      image_url: https://www.lds.org/bc/content/shared/content/images/gospel-library/magazine/fr09jan41_color.jpg
      song_title: I am a child of God
      music_url: http://broadcast.lds.org/churchmusic/MP3/1/2/words/2.mp3?download=true
    - id: my-heavenly-father-loves-me
      image_url: https://easter-fun.info/wp-content/uploads/04/lds-easter-message-2018-easter-lily-1024x1024.jpg
      song_title: My Heavenly Father loves me
      music_url: http://broadcast.lds.org/churchmusic/MP3/1/2/words/228.mp3?download=true
