souderton_ward:
  boxes:
    - id: im-trying-to-be-like-jesus
      image_url: http://2.bp.blogspot.com/-4Ly7WSDDIzo/UBtewib0zbI/AAAAAAAAAnM/3tLlSFiNX4w/w1200-h630-p-k-no-nu/Jesus-Children-2010+Outline+Cover.png
      song_title: I'm trying to be like Jesus
      music_url: http://media2.ldscdn.org/assets/music/childrens-songbook/2002-01-0740-im-trying-to-be-like-jesus-music-only-192k-eng.mp3?download=true
      